Add shared GitHub Actions workflow for ruby
theforeman/foreman_default_hostgroup pull request #62
Opened 2024-01-25 14:14 UTC by archanaserver

2024-01-26 11:47 UTC, ekohl commented on .github/workflows/ruby_ci.yml
> +on: pull_request
Can you change this to also test push to the develop branch?

2024-01-26 11:49 UTC, ekohl requested changes
https://github.com/theforeman/foreman_default_hostgroup/pull/60 needs to be addressed before this can pass.

2024-01-26 11:49 UTC, ekohl commented on Gemfile
You need to make sure rubocop is in here. Probably easier to depend on `theforeman-rubocop`.

2024-01-30 08:51 UTC, archanaserver commented
WIP https://github.com/theforeman/foreman_default_hostgroup/pull/63

2024-02-22 15:24 UTC, ekohl commented
Please rebase now that #63 is merged.

2024-02-27 10:40 UTC, ekohl commented
Could you implement what https://github.com/theforeman/foreman_default_hostgroup/pull/60#discussion_r1348314077 suggests? Otherwise it's broken.

2024-02-27 11:46 UTC, archanaserver commented
@ekohl after making https://github.com/theforeman/foreman_default_hostgroup/pull/62/commits/d6874423adc1f91276a6690fbad853222dab48d5 changes, at this point i'm not sure what to look for to resolve this issue.

2024-02-27 14:43 UTC, ekohl requested changes
I think as part cbf79fe7e8a63624a39bc77d07d0e60d9166a78c we should have removed this bit:
https://github.com/theforeman/foreman_default_hostgroup/blob/c4bb39d72d98ddb96ecf7fac7f73aadff0aa45b7/test/unit/default_hostgroup_test.rb#L17-L27

Because of the settings DSL refactor and we can safely rely on the setting existing. But at the very least, drop the category bit there.

2024-04-18 15:21 UTC, ekohl commented
I get the impression it's not patching the class, for whatever reason. It's unclear if this is also a problem outside of the tests.

2024-05-09 09:59 UTC, archanaserver commented
@ekohl I still don't understand what I have to do here, do you have any other thoughts?

2024-07-19 20:24 UTC, evgeni commented
> I get the impression it's not patching the class, for whatever reason. It's unclear if this is also a problem outside of the tests.

It's patching the class just fine.
The tests use the wrong class (Host::Managed, not HostFactImporter!) which didn't have a `import_facts` since Foreman 2.2 (https://github.com/theforeman/foreman/commit/5253d21ed7d690e80e595a075d06f96d2e211e8c)

2024-07-19 20:35 UTC, evgeni commented
Well, the "real" problem is 66ad79c80321893084a1d19a26ce300ad0abb341 moved the patching from `Host` to `HostFactImporter`, but now the methods do not really make sense… IMHO

But at least they work?

2024-07-20 14:51 UTC, ekohl approved these changes

2024-07-20 14:51 UTC, merged